#!/bin/ash

export PATH=/sbin:/bin:/usr/sbin:/usr/bin
export HOME=/home/root
export USER=root
export ELM_ENGINE=fb
export ELM_FONT_PATH=/usr/share/fonts

mount -t proc none /proc
mount -t sysfs none /sys
mount -t tmpfs none /tmp

echo
echo Hello World
echo

dropbear

/bin/ash -l
