#!/bin/sh

case "$1" in
    start)
	ip link set usb0 up
	ip addr add 192.168.0.202/24 dev usb0
	ip route add default via 192.168.0.200
	echo nameserver 208.67.222.222 > /etc/resolv.conf
	echo nameserver 208.67.220.220 >> /etc/resolv.conf
	;;
    stop)
	ip link set usb0 down
	;;
    restart)
	$0 stop
	$0 start
	;;
    *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
	;;
esac

exit 0
