#!/bin/sh

. /etc/profile

mount -t proc proc /proc
mount -t sysfs sysfs /sys
mount -t devtmpfs devtmpfs /dev
mkdir /dev/pts && mount -t devpts devpts /dev/pts

mount -n -o remount,noatime,rw /

/sbin/qi-bootmenu `sed -r -n 's/.*qi-bootmenu-args="([^"]*).*/\1/p' /proc/cmdline` &

/etc/init.d/networking start
/etc/init.d/dropbear start

setsid cttyhack sh
