#!/bin/sh

case "$1" in
    start)
	syslogd || echo "Starting syslogd failed."
	klogd || echo "Starting klogd failed."
	;;
    stop)
	killall syslogd
	killall klogd
	;;
    restart)
	$0 stop
	$0 start
	;;
    *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
	;;
esac

exit 0
